version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: clickit
      POSTGRES_USER: clickit
      POSTGRES_PASSWORD: clickit_pass
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/usr/src/app

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - '9000:9000'

volumes:
  db-data:
  minio-data:
